#!/usr/bin/env bash
#
# Description:
# Launch the corresponding OCI Container of an Image.
#

###############################################################################

# Get Arguments
IMAGE_NAME="$1"
CODE_SERVER_PASSWORD="$2"
WORKSPACE_DIR="$3"

# Check if number of arguments provided is zero
if [ $# -lt 2 ]; then
    echo ""
    echo "You need to provide an image name, a code-server access password, "
    echo "and optionally a projects workspace to mount."
    echo "Examples:"
    echo "  - container_start my_image_a mypassword1234"
    echo "  - container_start my_image_b myotherpwd5678"
    echo "  - container_start my_image_c mypwd9876 ~/my_projects"
    echo ""
    exit 1
fi

###############################################################################

# Mount points
WORKSPACE_MOUNT_DIR="/home/user/projects"
CODE_SETTINGS_TO_MOUNT="${PWD}/ides/${IMAGE_NAME}/code_config/settings.json"
CODE_SERVER_USER_DATA_DIR="/home/user/.local/share/code-server"
CODE_SETTINGS_MOUNT_POINT="${CODE_SERVER_USER_DATA_DIR}/User/settings.json"

###############################################################################

# Set Container Mount Volume for projects workspace
if [ -n "$WORKSPACE_DIR" ]; then
    WORKSPACE_DIR_NAME=`basename ${WORKSPACE_DIR}`
    WORKSPACE_MOUNT_POINT="${WORKSPACE_MOUNT_DIR}/${WORKSPACE_DIR_NAME}"
    VOLUME_OPT_WS=(--volume="${WORKSPACE_DIR}:${WORKSPACE_MOUNT_POINT}")
else
    VOLUME_OPT_WS=""
fi

# Allow root user to run GUI Applications (connect to X server)
#xhost +local:root

# Not for this type of containers (for X11 GUI Windows and HW devices access):
# --env="DISPLAY=${DISPLAY}" \
# --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
# --volume="/dev:/dev" \

# Launch the image container
podman run -it --network="host" --rm \
    --env="PASSWORD=${CODE_SERVER_PASSWORD}" \
    --volume="${CODE_SETTINGS_TO_MOUNT}:${CODE_SETTINGS_MOUNT_POINT}" \
    $VOLUME_OPT_WS \
    $IMAGE_NAME

###############################################################################

exit 0

###############################################################################
