#!/usr/bin/env bash
#
# Description:
# Build and create the specififed OCI Container Image.
#

###############################################################################

# Get Arguments
IMAGE_NAME="$1"
CONTAINER_FILE_PATH="$2"

# Check if correct number of arguments has been provided
if [ $# -lt 2 ]; then
    echo ""
    echo "You need to provide a image name and directory with Containerfile to"
    echo "build."
    echo "Examples:"
    echo "  container_build a_image_name ./path/to/containerfile/directory"
    echo ""
    exit 1
fi

# Launch Container Image Build
podman build --network="host" -t $IMAGE_NAME $CONTAINER_FILE_PATH
BUILD_RESULT=$?

# Remove dangling images if build succes
if [ $BUILD_RESULT -eq 0 ]; then
    echo "Build success"
    any_dangling_image=`podman images | grep -e "none"`
    if [ ! -z "${any_dangling_image}" ]; then
        echo "Removing dangling images"
        podman rmi -f $(podman images --filter "dangling=true" -q --no-trunc)
    fi
fi

###############################################################################

exit 0
