#!/usr/bin/env bash
#
# Description:
# Build and create the specififed Docker Image.
#

###############################################################################

# Get Arguments
IMAGE_NAME="$1"
DOCKER_FILE="$2"

# Check if correct number of arguments has been provided
if [ $# -lt 2 ]; then
    echo ""
    echo "You need to provide a image name and Dockerfile to build."
    echo "Examples:"
    echo "  docker_install arm_c_cpp ../images/arm_c_cpp/"
    echo "  docker_install x86_64_c_cpp ../images/x86_64_c_cpp/"
    echo "  docker_install python ../images/python/"
    echo ""
    exit 1
fi

# Launch Docker Image Build
docker build --network="host" -t $IMAGE_NAME $DOCKER_FILE

###############################################################################

exit 0
