#!/usr/bin/env bash
#
# Description:
# Stop a Docker Container from Docker Image Name.
#

###############################################################################

# Get Docker images names from each provided argument
docker_image_name=()
for i in "$@"
do
    docker_image_name+=("${i}")
done

# Check if any docker image has been provided
if [ ${#docker_image_name[@]} -eq 0 ]; then
    echo ""
    echo "You need to provide a Docker Image Name to stop"
    echo "Examples:"
    echo "  docker_stop a_image_name"
    echo "  docker_stop a_image_name another_one why_not_other"
    echo ""
    exit 1
fi

# For each Image Name provided
for img_name in "$docker_image_name"
do
    # Get Docker Container ID from Image Name
    container_id=`docker ps -a | grep -e "{img_name}" | cut -d' ' -f1`

    # Stop Docker Container
    docker stop $container_id
done

###############################################################################

echo ""
echo "Container Stopped"
echo ""

exit 0
